#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 219651-web-01 100.26.158.33:80 check
   server 219651-web-02 34.234.201.10:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
