#!/usr/bin/env bash
# reads, cuts the formats the /etc/passwd file into a sentence
IFS=":"
while read -r line; do
	read -r -a cols <<< "$line"
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "${cols[0]}" "${cols[3]}" "${cols[5]}" "${cols[6]}" "${cols[2]}" "${cols[1]}" "${cols[4]}"
done < /etc/passwd
